name: test

on:
  - push
  - pull_request
  - pull_request_target

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - if: github.event_name == 'push'
        run: |
          git fetch && git checkout "${GITHUB_REF#refs/heads/}"
      - if: github.event_name == 'pull_request' || github.event_name == 'pull_request_target'
        env:
          REF: ${{ github.head_ref }}
        run: |
          git fetch && git checkout "${REF}"
      - run: yarn --silent reg-suit sync-expected 2>&1 | tee stdout.txt
      - run: tail -n 1 stdout.txt | grep -v 'key is null'
